version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
          - "./:/volumes"
    environment:
      MONGODB_USER: "admin"
      MONGODB_PASSWD: "admin"
