version: "3.9"
services:
  rest-api:
    container_name: rest-api
    ports:
      - "8080:8080"
    networks:
      - my_network
    image: "filippradler/ctc_2022:latest"
    depends_on:
      - mongo_db
    environment:
        - "MONGOURI=mongodb://mongo_db:27017"
  mongo_db:
    container_name: mongodb
    ports:
      - "27017:27017"
    image: "mongo:5"
    networks:
      - my_network
    volumes:
          - ./mongo-volume:/data/db

networks:
  my_network:
    driver: bridge
